/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu6;


import minggu6.controllers.MenuView;
import minggu6.models.StatusPresensi;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        MenuView menu = new MenuView();
        menu.render();
    }


    
}
