/*
 * This source file was generated by the Gradle 'init' task
 */
package minggu6;


// import minggu6.views.MenuView;
import minggu6.util.Database;
import minggu6.views.MenuView;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
        MenuView menu = new MenuView();
        menu.render();
        Database db = new Database();
        db.connect();
        // MahasiswaRepository mhsRepo = new MahasiswaRepository();
        // mhsRepo.printNilaiAkhir("2102001", "IF101");


    }


    
}
